FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* /app/
RUN npm install

COPY . /app
RUN npm run build

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app /app

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
