[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flightcomp-api"
version = "0.1.0"
description = "Aervyx backend"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.116.0",
  "uvicorn[standard]>=0.35.0",
  "sqlalchemy>=2.0.40",
  "alembic>=1.16.0",
  "psycopg[binary]>=3.2.0",
  "pydantic-settings>=2.10.0",
  "python-multipart>=0.0.20",
  "passlib[bcrypt]>=1.7.4",
  "bcrypt<5",
  "python-jose[cryptography]>=3.4.0",
  "shapely>=2.1.0",
  "aiomqtt>=2.3.0",
  "pytest>=8.4.0",
  "httpx>=0.28.0",
  "google-auth>=2.38.0",
  "requests>=2.32.0",
  "slowapi>=0.1.9",
  "cfgrib>=0.9.10",
  "numpy>=1.26.0"
]

[tool.setuptools.packages.find]
include = ["app*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
